In [14]:
import pandas as pd
import numpy as np

In [15]:
df = np.array([[1,2, np.nan], [3, np.nan, 7], [np.nan, 6,8]])

In [16]:
df

array([[ 1.,  2., nan],
       [ 3., nan,  7.],
       [nan,  6.,  8.]])

In [6]:
!pip install fancyimpute

  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
  Using cached clarabel-0.11.1-cp39-abi3-win_amd64.whl.metadata (4.9 kB)
   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.8 MB ?


[notice] A new release of pip is available: 24.2 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [17]:
from fancyimpute import IterativeImputer as MICE

In [18]:
mice_imputer = MICE()

In [19]:
x_imputed = mice_imputer.fit_transform(df)

In [20]:
x_imputed

array([[1.        , 2.        , 5.89670921],
       [3.        , 4.09825687, 7.        ],
       [4.81281379, 6.        , 8.        ]])

# Case 2  

In [21]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

# sample data frame
df = np.array([[1,2, np.nan], [3, np.nan, 7], [np.nan, 6,8]]) 


In [22]:
imputer = IterativeImputer(max_iter = 10, imputation_order = 'ascending')

In [23]:
x_imputed_new  = imputer.fit_transform(df)

In [24]:
x_imputed

array([[1.        , 2.        , 5.89670921],
       [3.        , 4.09825687, 7.        ],
       [4.81281379, 6.        , 8.        ]])

In [25]:
x_imputed_new

array([[1.        , 2.        , 5.89670921],
       [3.        , 4.09825687, 7.        ],
       [4.81281379, 6.        , 8.        ]])